spring:
  # Mysql
  datasource:
    url: jdbc:mysql://localhost:3306/sysadmin?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 88888888
    
redis:
  host: 127.0.0.1
  port: 6379
  password: 
  timeout: 5000    