spring:
  # Mysql配置
  datasource:
     url: jdbc:mysql://localhost:3306/sysadmin?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
     username: root
     password: 88888888
  # Redis配置
  redis:
    database: 10
    host: 47.112.121.234
    password: redis2019TEST
    timeout: 10000    