spring:
  # Mysql配置
  datasource:
     url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
     username: root
     password: 88888888
     
  # Redis配置
  redis:
    database: 0
    host: 127.0.0.1
    password: 
    timeout: 30000
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: 30000
        min-idle: 0   